### ISSUE TITLE
Rename repo to proposal-builtin-modules

### ISSUE THREAD

**Issue by MylesBorins** [tc39/proposal-javascript-standard-library#57] opened 2019-10-08 19:27 UTC
I was under the impression that at a previous meeting there was a decision to rename this proposal. Am I mistaken?

**Comment by chicoxyzzy** [comment] 2019-10-08 19:56
Yes, it was June 2019 meeting in Berlin https://github.com/tc39/tc39-notes/blob/master/meetings/2019-06/june-5.md#conclusionresolution-8

**Comment by chicoxyzzy** [comment] 2019-10-08 20:01
Duplicate of https://github.com/tc39/proposal-javascript-standard-library/issues/53 🙂

**Closed** 2019-10-10 12:57 UTC
